#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

[ "$(git symbolic-ref --short -q HEAD)" = "dev"    ] && npm version patch --no-git-tag-version
[ "$(git symbolic-ref --short -q HEAD)" = "master" ] && npm version minor --no-git-tag-version
npm run build
git add dist/
git add package*.json
